### ISSUE TITLE
multiple flipviews in a view cause crash?

### ISSUE THREAD

**Issue by sxchao** [Dillion/iOS-Flip-Transform#4]
Hello, I recently downloaded your code, and think it's amazing! One thing I noticed was, when I tried to create an additional couple of flipviews, occassionally when I panned for a while, the last pan caused the animation to slow down all of a sudden, and then the app crashed. Have you ever experienced this? Do you know what the potential cause could be? This is on both iPad 5.0 Simulator, as well as iPad 2 running iOS 5.

This appeared to be more pronounced when I added one more flipview to the demo, that was a vertical flip. Again, it wasn't always 100% consistent though. With a couple more horizontal flipviews, it didn't seem to happen as much, but still did happen from time to time.

**Comment by sxchao** [comment]
FYI, for each flipview, I initialized a new animationdelegate, flipview, and panregion. I reuse the recognizer in the 'panned' method, by assigning an int a value based on which panregion was touched, then doing a switch statement on that int.

**Comment by rpedroni** [comment]
I didn't try this using panning but with triggered flipviews, I inserted all animation delegates into a NSMutableArray and I am able to animate each flip view independently without any issues.

**Comment by sxchao** [comment]
Issue seems to have resolved itself during the course of my building out the app.

**Comment by ghost** [comment]
@sxchao how did you make efficient the multiple flipviews?
